### ISSUE TITLE
RaceApp not opening

### ISSUE THREAD

**Issue by Jimb0k** [censorfriendly/esx-racing#1]
Is there any requirement to run the app? When using /raceApp nui focus turns on but nothing shows up.

**Comment by censorfriendly** [comment]
You will need to build the project. Npm install inside html folder. Then run npm run build

**Comment by censorfriendly** [comment]
This is a good point I will add the compiles code to the repo to make it easier on people trying to use

**Comment by Jimb0k** [comment]
Got it, thank you!
